all:
	g++ -I SDL2/include -I include -L SDL2/lib -o bin/Space_Invaders main.cpp src/level.cpp src/max_score.cpp src/select_level.cpp src/ufo.cpp src/menu.cpp src/main_menu.cpp src/score.cpp src/enemies.cpp src/spaceship.cpp src/global.cpp src/text.cpp src/init.cpp src/textures.cpp src/buttons.cpp -l mingw32 -l SDL2main -l SDL2 -l SDL2_ttf -l SDL2_image
